spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.server.mvc.routes[0].id=catalog-service
spring.cloud.gateway.server.mvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.mvc.routes[0].predicates[0]=Path=/api/v1/catalog/**
